export const environment = {
  production: true,
  baseUrl:'http://ec2-54-153-58-93.us-west-1.compute.amazonaws.com',
  //baseUrl:'http://localhost',
  puertoApiAdmonCatalogos:'3005',
  regiones:'/regiones',
  especialidades:'/especialidades',
  sucursales:'/sucursales',
  productos:'/productos',
  productos2:'/productos2',
  tiposProducto:'/tipos-producto',
  salsas:'/salsas',
  relacion_etps:'/relacion_especialidad_tamanio_precio_sucursal',
  promociones_especiales:'/promociones_especiales',
  relacion_pes:'/relacion_promociones_especiales_sucursal',
};
