export const environment = {
  production: true,
  //Servidor AWS_AppixSoftware 30Nov2025
  //baseUrl:'http://ec2-54-144-58-67.compute-1.amazonaws.com',
  baseUrl:'http://api.cheesepizza.com.mx',
  baseApiCatalogos: 'http://admin.cheesepizza.com.mx',
  //baseUrl:'http://localhost',
  puertoApiAdmonCatalogos:'3005',
  regiones:'/regiones',
  especialidades:'/especialidades',
  dameListadoEspecialidadesNoCombinanTodosLosTamanios:'/especialidadesNoCombinanTodosTamanios',
  sucursales:'/sucursales',
  productos:'/productos',
  productos2:'/productos2',
  tiposProducto:'/tipos-producto',
  tamaniosPizza:'/tamanios-pizza',
  salsas:'/salsas',
  orillas:'/orillas',
  pizzas:'/pizzas',
  categorias:'/categorias',
  ingredientes:'/ingredientes',
  relacion_orilla_sucursal:'/relacion_orilla_sucursal',
  relacion_pizza_sucursal:'/relacion_pizza_sucursal',
  relacion_producto_sucursal:'/relacion_producto_sucursal',
  relacion_salsa_sucursal:'/relacion_salsa_sucursal',
  dameListadoPizzasNoEstanEnRPS:'/dameListadoPizzasNoEstanEnRPS',
  dameListadoOrillasNoEstanEnROS:'/dameListadoOrillasNoEstanEnROS',
  dameListadoProductosNoEstanEnRPS:'/dameListadoProductosNoEstanEnRPS',
  dameListadoSalsasNoEstanEnRSS:'/dameListadoSalsasNoEstanEnRSS',
  relacion_etps:'/relacion_especialidad_tamanio_precio_sucursal',
  promociones_especiales:'/promociones_especiales',
  promociones_especiales_no:'/promociones_especiales_no',
  relacion_pes:'/relacion_promociones_especiales_sucursal',
  dameListadoPromocionesEspecialesNoEstanEnRPE:'dameListadoPromocionesEspecialesNoEstanEnRPE/',
};
