export const environment = {
  production: true,
  //baseUrl:'http://ec2-54-153-58-93.us-west-1.compute.amazonaws.com',
  baseUrl:'http://ec2-54-144-58-67.compute-1.amazonaws.com',
  //baseUrl:'http://localhost',
  puertoApiAdmonCatalogos:'3005',
  regiones:'/regiones',
  especialidades:'/especialidades',
  sucursales:'/sucursales',
  productos:'/productos',
  tiposProducto:'/tipos-producto',
  tamaniosPizza:'/tamanios-pizza',
  salsas:'/salsas',
  relacion_etps:'/relacion_especialidad_tamanio_precio_sucursal',
  promocion_especial:'/promociones_especiales',
  promociones_especiales_no:'/promociones_especiales_no',
  relacion_pes:'/relacion_promociones_especiales_sucursal',
};
